### ISSUE TITLE
RigidBody2D body_entered signal not emitting on collisions when bounce is enabled on the physics material 

### ISSUE THREAD

**Issue by catweaselirl** [appsinacup/godot-rapier-2d#29]
**Describe the bug**
On a RigidBody2D node with a circle collision shape and a physics material with bounce set to 1, the built in body_entered signal is not emitted on collisions with StaticBody2Ds.

**To Reproduce**
1. Create a RigidBody2D node
2. Give it a CollisionShape2D (Not sure if shape matters, but mine is a circle)
3. Give the RigidBody2D a physics material with bounce set to 1
4. Upon collision with a StaticBody2D node, the built in body_entered signal is never emitted

**Expected behavior**
The body_entered signal should be emitted (Works properly on both Box2D and GodotPhysics)

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11
 - Godot Version: 4.2 beta 4

**Comment by Ughuuu** [comment]
Investigating.
