### ISSUE TITLE
PhysicsDirectSpaceState2D.intersect_shape not working

### ISSUE THREAD

**Issue by bjomp** [appsinacup/godot-rapier-2d#31]
```gdscript
extends Node2D

var query: PhysicsShapeQueryParameters2D

func _ready():
	# 1 by 1 square at origin
	var shape: RID = PhysicsServer2D.rectangle_shape_create()
	PhysicsServer2D.shape_set_data(shape, Vector2(0.5, 0.5))
	var body: RID = PhysicsServer2D.body_create()
	PhysicsServer2D.body_set_space(body, get_world_2d().get_space())
	PhysicsServer2D.body_add_shape(body, shape)
	PhysicsServer2D.body_set_state(body, PhysicsServer2D.BODY_STATE_TRANSFORM, Transform2D(0, Vector2(0, 0)))
	PhysicsServer2D.body_set_mode(body, PhysicsServer2D.BODY_MODE_STATIC)
	
	# circle query at 10, 10 with radius 100
	var circle := CircleShape2D.new()
	circle.radius = 100
	
	query = PhysicsShapeQueryParameters2D.new()
	query.shape = circle
	query.transform = Transform2D(0, Vector2(10, 10))
	
func _physics_process(delta):
	var direct_space_state := get_world_2d().direct_space_state
	var results := direct_space_state.intersect_shape(query)
	print(results.size())
```
Only prints ``0`` on Rapier2D, will print ``1`` on default

**Comment by Ughuuu** [comment]
Investigating.

**Comment by Ughuuu** [comment]
Not sure what it has right now, but I saw that if the shape is child of a physicsbody, it works. Not sure why, will keep on investigating.

**Comment by Ughuuu** [comment]
The problem seems to be I was using the motion parameter for the test, and if the motion is 0,0 the result is not returned. Instead I ended up in cases where motion is used(other methods, not this) and motion is 0,0, put a very small motion(eg 0.00001,0.00001) so we get a result.
For this method, I used internally instead intersect_shape of rapier.

**Comment by Ughuuu** [comment]
Nevermind, intersect shape should work with motion as well. Putting then motion a small number in your case, and calling it a day. And also enabling intersect in place for intersect shape method, and others except cast_shape.
