### ISSUE TITLE
CharacterBody has issues with tile edges

### ISSUE THREAD

**Issue by starblinky** [appsinacup/godot-rapier-2d#59]
https://github.com/appsinacup/godot-rapier-2d/assets/51274080/9baa4ed1-f04a-455b-889d-d375ef30d894

I have tried this with the box shaped and pill shaped character colliders and with the same result. It gets stuck when trying to jump and holding movement towards the wall. 

CharacterBody collider seems to penetrate into the wall.

**Comment by Ughuuu** [comment]
Thank you for the issue, will investigate.

**Comment by Ughuuu** [comment]
Tried it locally and it doesn't occur in my cases.  If you can provide a test project, I can take a look. Closing until then.
Also update the issue with godot version, rapier version.
