### ISSUE TITLE
Project won't open after installing any of the plugin versions from asset store

### ISSUE THREAD

**Issue by abFrancisco** [appsinacup/godot-rapier-2d#62]
**Describe the bug**
Project won't open after installing any of the plugin versions from asset store and reloading the project, no crash log files that i could find from godot engine.

**To Reproduce**

1 open godot 4.2.1
2 create a project
3 install godot rapier from asset store
4 restart engine or reload project
5 crashes

**Expected behavior**

shouldnt crash

**Environment (please complete the following information):**

Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 Threads)

**Example project(zip)**

New project

**Comment by Ughuuu** [comment]
What version of godot-rapier-2d are you using?

**Comment by Ughuuu** [comment]
Yea, I can reproduce the issue. It's related to the new Fluid2D changes added:

```
4   libsystem_platform.dylib      	       0x1860b3584 _sigtramp + 56
5   libphysics_server_rapier2d.macos.template_debug.dylib	       0x121c9f830 RapierPhysicsServer2D::fluid_create() + 88
6   libphysics_server_rapier2d.macos.template_debug.dylib	       0x121c9f830 RapierPhysicsServer2D::fluid_create() + 88
7   libphysics_server_rapier2d.macos.template_debug.dylib	       0x121cb2b20 Fluid2D::Fluid2D() + 208
8   libphysics_server_rapier2d.macos.template_debug.dylib	       0x121c84660 Fluid2D::create(void*) + 36
```

Will make a hotfix.
