### ISSUE TITLE
Problems with velocities, default body rotation, colliders get stuck, events not getting called, etc.

### ISSUE THREAD

**Issue by GeminiSquishGames** [appsinacup/godot-rapier-2d#71]
It's hard to describe what I'm experiencing. All I can say is I had a working asteroid-like game going, and now very few things work as they do with the default.

The bullet speeds are much slower and aren't registering hits. 

I spawn asteroids in with a random linear_velocity and angular_velocity set so they distribute that as they move around, but now they simply have a constant rotation and are not distributing the angular velocity properly, or at all really. As if they are on a constant torquing motor and angular velocity keeps the same value without dampening. This is the SMID faster version. But it seems like no rotation happens in slower ED version.

My player rigid body would point at the mouse cursor but it goes out of sync now when things kind of collide but get stuck to it. It seems better but still happens in slower ED version.

The shield is just a collider alongside the ship's colliders that deactivates when not in use, but it seems like I can't deactivate the collider like I was before and it's always on. I could perhaps instance it and free it but it also grows and shrinks by manipulating the circle shape's radius, this also no longer works at all, but did with default. Both versions do this.

If that collider is touching anything else it will get the RBody stuck. The ship will no longer gain directional thrust and just gets stuck on the object.  the slower ED version is much better about this, doesn't seem to get stuck.

Collectables that once collected properly no longer do so and simply push the ship around if I manually override the shield off in the editor during runtime. So it seems like the layers are not working properly. This happens in faster version SIMD, the slower ED will collect when hitting the always on sheild

As it is I can't really use the addon to replace the default physics system at this time as I have no control over these issues and have no idea what is wrong or what to do.

Edit: Also, move_toward seems to automatically face in the direction in the faster SIMD one, objects that were not meant to rotate now do. Default does not. It also seems to turn toward using the bottom of the rigid body, as though down is forward. The default is right is forward facing. May be why the rotation of the ship doesn't follow the mouse as well. also updated to which versions these problems are in.

Overlapping spawns seem to need a lot more leeway or they create way more velocity on objects. Can just make sure overlaping objects dampen or spawn further away before applying any force. both versions.

**Comment by Ughuuu** [comment]
I would say you make individual bugs for each problem if you want them fixed. Also add reproducible projects(Without the addon) and description as to what should happen. Thanks.

Sorry for the problems you are experiencing also.

**Comment by Ughuuu** [comment]
Closing this issue anyway, as it doesn't fit perfectly an issue, it's more like multiple issues. Open new issues as described above, by at least putting a reproducible project(so I can test/try fix) and version of godot used and rapier addon used.

**Comment by GeminiSquishGames** [comment]
Cool beans. The easiest way is to add you to the repo for the project, I'll get around to that todaynight and separate all the issues. Sorry about the Wall of Issues, I was doing it all in real time, should have used a word processor and separated them first... <.<
