### ISSUE TITLE
PinJoint2D - Rotation very stiff

### ISSUE THREAD

**Issue by greycheeked** [appsinacup/godot-rapier-2d#96]
I have tried the PinJoint2D. I'm not so much interested in the motor as the fact that you can specify an angle range. It works surprisingly well.

I noticed that the two bodies, which are connected to each other, no longer rotate freely around each other, as was previously the case with the PinJoint2D. The connection is almost rigid. You can no longer create loosely swinging ropes, for example.

Would it be possible to restore free rotation? Or is this simply not possible with Rapier2D?

**Comment by Ughuuu** [comment]
Free rotation with angle range? I am unsure what the ask is. You can disable angle range and then it should have free rotation, no?

**Comment by greycheeked** [comment]
I left out the angle limits to show what I mean.
In the first video (Godot Physics), the limbs can rotate freely. In the second (Rapier2D), they appear to be rusted in place.

https://github.com/appsinacup/godot-rapier-2d/assets/92092511/5146fe16-0486-4cbf-b8e0-37fbce82d919

https://github.com/appsinacup/godot-rapier-2d/assets/92092511/6971314a-25a6-4099-a1e8-1f1620e253ef

**Comment by Ughuuu** [comment]
Interesting, can you upload the demo project you have in that video?

**Comment by greycheeked** [comment]
I removed the "addons" and "samples" folders to keep it small. (I had both Box2D and Rapier2D as addons in the demo project, both in the current Git version).

[PinJoint2DAngLimit.zip](https://github.com/appsinacup/godot-rapier-2d/files/15286593/PinJoint2DAngLimit.zip)

**Comment by Ughuuu** [comment]
This is really strange, I don't think I noticed until now that the joints work like this. I have tried in the past working with joints and it seemed to have worked well.

I am pretty sure maybe something changed, because I have a softbody addon that uses this exact feature, and the rotation works there. Hm..

**Comment by Ughuuu** [comment]
Ok, after further investigation, it seems the inertia is wrong on shapes.
If I set inertia to custom and set inertia to 1, everything works(in rapier).
If I leave it to auto, it doesn't.

I am assuming it's related to my change where I divide everything by 100 to go from pixel to meters. And I don't divide inertia.

**Comment by Ughuuu** [comment]
So until this is fixed, as a workaround, you can set inertia to custom and set it to 1.

**Comment by greycheeked** [comment]
Unfortunately, that doesn't work for me. Maybe I just got it wrong. I have done the following in the inspector for all RigidBody2Ds: entered a 1 under RigidBody2D > Mass Distribution > Inertia. Nothing else.
This causes the ragdoll to fly apart after it hits the ground. The individual limbs and the torso move away from each other and whirl around each other without settling down again.

**Comment by Ughuuu** [comment]
Right, if you set custom inertia it also sets the custom center to 0,0.
However i saw it shapes are not centred to 0,0
If you center the shape and move the body, it should work.
I will have a fix though soon, as this is quite a basic functionality.

**Comment by Ughuuu** [comment]
Ok, its related to the joint motor. Even if I don't set up motor, the motor is set to 0. However, in this case, rapier tries to stop the object.

The fix will be in case of motor being 0, to set the motor force as well to 0. If not, will set the motor force to Real::MAX for now.
