### ISSUE TITLE
intersect_shape with a circle with it's origin inside rectangle fails to detect collision

### ISSUE THREAD

**Issue by AntonBergaker** [appsinacup/godot-rapier-2d#97]
**Describe the bug**
When calling intersect_shape with a circle shape, if it's origin is inside a rectangle, that rectangle won't be detected.

**To Reproduce**
1. Call intersect_shape with a circle inside a rectangle
2. Observe it is not detected

**Expected behavior**
The rectangle shape should be detected

**Screenshots**
Easiest to see with the attached project

**Environment (please complete the following information):**
 - OS: Windows
 - Version: Godot Rapier 2D v0.6.20
 - Godot Version: 4.2.2
 - Type: Single simd

**Example project(zip)**

[testoverlap.zip](https://github.com/appsinacup/godot-rapier-2d/files/15285741/testoverlap.zip)

**Comment by Ughuuu** [comment]
Looked at this, wasn't immediately obvious what is wrong with it. However I have hope, in version 0.19 the api changed to allow more options for shape_collide. I'll try that when I update to 0.19 completely(rn I am blocked by salva not working with 0.19, looking at it but might just wait for it to receive support by dimforge).

**Comment by Ughuuu** [comment]
Taking a look again at it, now that I fixed the build for 0.19.

**Comment by Ughuuu** [comment]
Looks like it got fixed. Probably by the 0.19 update on shape_case where they now expose a field "intersect_at_start" or something similar.
