### ISSUE TITLE
Condition "monitored_objects.has(handle_pair_hash)" is true

### ISSUE THREAD

**Issue by garf** [appsinacup/godot-rapier-2d#99]
**Describe the bug**
Engine shows these errors in debug console

```monolog
E 0:00:18:0202   RapierArea2D::on_body_enter: Condition "monitored_objects.has(handle_pair_hash)" is true.
  <C++ Source>   src\bodies\rapier_area_2d.cpp:50 @ RapierArea2D::on_body_enter()
```

**To Reproduce**
Just use it to detect collisions

**Expected behavior**
No errors generated

**Screenshots**
![image](https://github.com/appsinacup/godot-rapier-2d/assets/1891709/1d13e796-f4e0-461e-b420-fe577643b3f9)

**Environment (please complete the following information):**
 - OS: Windows
 - Version:  0.6.20 (Faster version with SIMD)
 - Godot Version: v4.3.dev6.mono.official [89850d553]

**Comment by Ughuuu** [comment]
Can you upload a project, it's not immediately obvious what `Just use it to detect collisions` means. Thanks

**Comment by garf** [comment]
@Ughuuu I added you as a collaborator to the repo. To reproduce you just have to start the game and when the character starts to hit the enemies or collide with them, you will see errors in debug panel.
Thank you!

**Comment by Ughuuu** [comment]
Tested your project, it seems like it would be better to disable the run on separate thread. Not 100% tested with the separate thread thingy, but at least on my machine it generates crash at times.
As for the error, seems like it's just an error generated by the fact that the object is removed when the area event happens. I think I can safely remove that error warning.

**Comment by garf** [comment]
BTW, I tried to disable a separate thread, and it still crashes from time to time. Have no idea why. Also logs say nothing. Will check further. Thank you again for testing!

**Comment by Ughuuu** [comment]
Hm, I wonder if I can reproduce somehow. About how often would you say the crash happens, or after how long time?

**Comment by garf** [comment]
Frequently. Usually after a minute or two of playing.

**Comment by Ughuuu** [comment]
My guess is it's because of the asserts most likely. There are a lot of asserts in the rapier wrapper.
After the rewrite of the code to rust, I will correctly handle these cases and not do asserts any more.
As a workaround, what you can do for now is change the .gdextension file to change in the editor to use the release version of the addon.
Eg. if you are on mac you would change from this:
```
macos.debug = "res://addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_debug.framework"
macos.release = "res://addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_release.framework"
```

to this:

```
macos.debug = "res://addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_release.framework"
macos.release = "res://addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.template_release.framework"
```

Or even easier, replace all template_debug in the extension with template_release.
The file name in question is godot-rapier2d.gdextension.

**Comment by garf** [comment]
Thank you! I will try to do it.

**Comment by obfuscatedgenerated** [comment]
Has the fix reached the SIMD package on the asset library yet? I'm still facing this

**Comment by Ughuuu** [comment]
It's possible after the rewrite the issue reappeared. The addon was rewritten from cpp to rust.

**Comment by Ughuuu** [comment]
However if the issue is still present open a new issue and put a reproducible example so i can debug it. Upload it as a zip rather than a private repo or anything.

Thanks

**Comment by Ughuuu** [comment]
Actuallt on the asset store it might not be latest version, you can try the latest from github first maybe also.

**Comment by obfuscatedgenerated** [comment]
I think I'm having the same issue as the original poster here though. In the commit just before migrating to rust, the assertion is replaced by returning early:
https://github.com/appsinacup/godot-rapier-physics/pull/100/commits/60414745dd345b2e91ec3cb0696ce01ad9753f1e

But then in the rust rewrite, this is made back into throwing an error:
https://github.com/appsinacup/godot-rapier-physics/blob/a7dfd18dccbbd4fadf3cf0aa77ab7db1935eee18/src/bodies/rapier_area.rs#L193

No release was made in between changing the cpp version to remove the assertion, and replacing everything with rust, so there is no github release in which this doesn't happen. I tried the rust version and the linked error was being thrown. I'm currently trying to compile a version after the change was made to the cpp source to see if it will stop (will update this comment when I've done so). I don't have a rust compiler and found the physics to be more stable in the cpp version anyway. Removing the linked error in the rust version would probably also "fix" it.

As for a repro project, I annoyingly can't figure out what triggers it. Seems to only be happening in my full game, which I'd rather not share. I appreciate this isn't very helpful, so sorry about that :(

Best of luck

**Comment by Ughuuu** [comment]
Right, i see, so removing the error is the fix probably then.

**Comment by obfuscatedgenerated** [comment]
> I'm currently trying to compile a version after the change was made to the cpp source
I couldn't get it to compile properly, but oh well

> so removing the error is the fix probably then.
I would guess, seemed to be the "fix" marked for this issue originally

**Comment by Ughuuu** [comment]
You are trying to compile from C++ code or Rust code? The Rust one you get compile errors? Are you following the steps for build form the documentation?

**Comment by Ughuuu** [comment]
Ah, right, there are some linking errors on main i am trying to fix. Not sure why they appear. They are only on windows.

**Comment by Ughuuu** [comment]
Build should be fixed now.
